const ActionTypes = {
	// Book management actions
	BOOKS_LOADING: 'BOOKS_LOADING',
	BOOKS_FAILED: 'BOOKS_FAILED',
	ADD_BOOKS: 'ADD_BOOKS',
	ADD_BOOK: 'ADD_BOOK',
	EDIT_BOOK: 'EDIT_BOOK',
	DELETE_BOOK: 'DELETE_BOOK',

	// Authentication actions
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGOUT_REQUEST: 'LOGOUT_REQUEST',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_FAILURE: 'LOGOUT_FAILURE',

	// User management actions
	EDIT_USER: 'EDIT_USER',
	EDIT_PASSWORD: 'EDIT_PASSWORD',
	ISSUES_LOADING: 'ISSUES_LOADING',
	ISSUES_FAILED: 'ISSUES_FAILED',
	ADD_ISSUES: 'ADD_ISSUES',
	ADD_ISSUE: 'ADD_ISSUE',
	RETURN_ISSUE: 'RETURN_ISSUE',
	USERS_LOADING: 'USERS_LOADING',
	USERS_FAILED: 'USERS_FAILED',
	ADD_USERS: 'ADD_USERS',
	USERS_FAILED: 'USERS_FAILED'
}
export default ActionTypes;